version: '3'
services:
  elasticsezzarch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  rabbitmq:
    image: rabbitmq
    restart: always
    ports: 
      - 15672:15672
  frontend:
    build: ./frontend
    ports:
      - '80:3000'
    volumes:
      - '.:/usr/src/app'
    working_dir: '/usr/src/app/frontend'
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/src/app'
    working_dir: '/usr/src/app/backend'
volumes:
  esdata1:
    driver: local
