version: '3'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    restart: always
    ports: 
      - 15672:15672
      - 5672:5672
    networks:
      - local
  frontend:
    build: ./frontend
    ports:
      - '80:3000'
      # Mount the app from host for hot-reload, except node_modules in case host is not linux
      # sass linux bind binary file needed
    volumes:
      - './frontend:/usr/src/frontend'
      - /usr/src/frontend/node_modules
    working_dir: '/usr/src/frontend'
    networks:
      - local
  api:
    build: ./api
    ports:
      - '8080:8080'
    volumes:
      - './api:/usr/src/api'
    working_dir: '/usr/src/api'
    networks:
      - local
networks:
  local:
    driver: bridge