version: '3'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    restart: always
    ports: 
      - 15672:15672 #RabbitMQ interface
  frontend:
    build: ./frontend
    ports:
      - '80:3000'
      # Mount the app from host for hot-reload, except node_modules in case host is not linux
      # sass linux bind binary file needed
    volumes:
      - './frontend:/usr/src/frontend'
      - /usr/src/frontend/node_modules
    working_dir: '/usr/src/frontend'
    links:
      - api
  api:
    build: ./api
    volumes:
      - './api:/usr/src/api'
    working_dir: '/usr/src/api'
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
  search-service:
    build: ./search-service
    volumes:
      - './search-service:/usr/src/search-service'
      - esdata1:/usr/share/elasticsearch/data
    working_dir: '/usr/src/search-service'
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200 # Optional just to debug
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
volumes:
  esdata1:
    driver: local
